name: translation_engine_deepl
description: 
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  translate_client:
    path: ../translate_client

dev_dependencies:
  test: ^1.0.0
